### PR TITLE
Add translations

### PR DESCRIPTION
**Pull request by shubhsherl**
@RocketChat/android

Add some translations

### CODE REVIEW

**Comment by divyanshub024** [comment]
@shubhsherl May I know how do translated these strings.

**Comment by shubhsherl** [comment]
@divyanshub024 I used Google translator and cross checked if the translation is correct by translating it to English again. Just to be double sure if the translation is correct.

**Comment by divyanshub024** [comment]
@shubhsherl Google translator is not a reliable option to translate language even if you double check it. I suggest you to only translate the language you know.

**Comment by shubhsherl** [comment]
Oh, okay...

**Comment by rafaelks** [comment]
Thanks for the contribution @shubhsherl, but we prefer the translation from native/fluent speakers  only and not translations from Google Translate. If you are native speaker or fluent in any language you're more than welcome to help us with these languages. Thanks!

**Pull request closed without merging**
