### PR TITLE
Fix JSON in member list

### LINKED ISSUE #275: Member List shows JSON
Your Rocket.Chat.Android version: (make sure you are running the latest) 1.0.11

When you open member list, this shows up:
screenshot_2017-05-04-22-00-31

### PR DESCRIPTION
**Pull request by gardenerik**
@RocketChat/android

Closes #275 

UsersOfRoomDialogFragment receives JSONArray of *JSONObjects* (not strings) at line 164.
As current code thinks that it receives JSONArray of Strings, it adds it to users ArrayList, as it is supposed to be username, but it is not - instead it converts JSONObject, that is in JSONArray to string. (I hope, that I made it clear by now :slightly_smiling_face: )

### CODE REVIEW

**Comment by laggedHero** [comment]
Thank you @ano95 ! It's wonderful to have you here with us.

But I need to consider older servers (people with their own not up to date deploy). Could you please make it so it works on both cases?

**Comment by gardenerik** [comment]
Of course I can :) After I update Android Studio 😄

**Comment by gardenerik** [comment]
@laggedHero Done 🙂

**Comment by laggedHero** [comment]
@ano95 Thank you so much

**Pull request merged**
