### PR TITLE
[BUG] Fixed (edited) msg shown when deleting a message

### LINKED ISSUE #1272: [BUG] (edited) is showing on system messages when deleting a message
@RocketChat/android

### PR DESCRIPTION
**Pull request by divyanshub024**
@RocketChat/android

Closes #1272

### CODE REVIEW

**Comment by philipbrito** [comment]
@divyanshub024 Could you check why this is not building the apk?

P.s: Try making a pull from `develop` and merge it with your branch.

**Comment by divyanshub024** [comment]
@filipedelimabrito I have made the changes. But Code-analysis is still failing. Do you know why?

**Comment by leonardoaramaki** [comment]
@divyanshub024 It's failing on the tests. There's a class file named MemoryMessagesRepositoryTest.kt that you can safely remove as the class it's unit testing is getting deprecated.

**Comment by divyanshub024** [comment]
@leonardoaramaki Thank you! I have made the changes.

**Review by philipbrito — APPROVED** [review]
Thanks for this PR @divyanshub024!

**Pull request merged**
