### PR TITLE
[WIP][NEW] Add tests for Authentication module

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
This PR is specific to GSoC'19 project (Improve test automation in Rocket.Chat Android Repo)

### Change Log
- Update CircleCI config to run unit test and UI tests separately
-  Add Codecov to the project to generate the code coverage report
-  Add UI test for the authentication module
-  Add unit test for the authentication module
-  Add readme for how to run tests on the local machine 

### We are also looking for your feedback on some issues mentioned [here](https://docs.google.com/document/d/1S8Eeef4nAoXE3E_XlhYDZBGXkbI2le0He4pivFmO-4c/edit?usp=sharing)

### CODE REVIEW

**Comment by philipbrito** [comment]
@GOVINDDIXIT Is it a WIP? Your tests (`ci/circleci: run-ui-tests`) is failing btw.

**Comment by GOVINDDIXIT** [comment]
Hi @filipedelimabrito We are stuck in running the ui tests on CircleCi.  I have mentioned this issue in detail in the wiki. Pls provide us your view on it. Thanks

**Comment by GOVINDDIXIT** [comment]
@filipedelimabrito I have updated to use Google docs for feedback, you can comment your views there

**Comment by ear-dev** [comment]
Hi @filipedelimabrito  I've been working with Govind as gsoc mentor.  Please do take a look at the wiki that Govind put together when you get a chance.  It describes the last two blocking issues we're having and we would like some suggestions from you if possible.  After these two issues are resolved, the rest of the tests will roll out easily I think...  Thanks!

**Comment by philipbrito** [comment]
@ear-dev I am not able to work on it in the couple of the nexts weeks. As soon as I'm able to work on it I'll let you know. Is there something blocking your project without my review here? If so, let me know.

c/c @GOVINDDIXIT

**Comment by ear-dev** [comment]
Thanks Filipe, I totally get that.  Our only issue is to keep the gsoc project on track, and your reviews will inform Govind's progress.  I can check with Sing and just get a sense from him about what our summer requirements and timeframe are.

**Comment by philipbrito** [comment]
@ear-dev As discussed internally with @GOVINDDIXIT some minutes ago this problem is also happening from his side (on his own CI) - so it means that something is wrong and needs to be fixed there (he told me that his CI is facing memory issues too).

I wasn't informed that my reviews here is part of the **each milestone** you guys have. That said I am unhappy to say that I am not able to work on it whenever a review is requested (we have some internal deadlines and I am also need to handle another GSoC project :) 

Maybe @Sing-Li can handle it better but my advise here is: Try fixing it from your side and also leave your reviews here as a mentor - ideally the PR should be submitted when it is supposed to be fine - which is not happening on the related and created ci task.

**Comment by ear-dev** [comment]
Ok, gottit.  We have done a full review on our end, but you are correct that this memory issue has not been solved.  I'm afraid that it might indicate that we need to use a paid version of CircleCi which would have more capacity, and I have no idea if RC wants to go in that direction.

**Comment by philipbrito** [comment]
@ear-dev Let discuss it internally. 👍

**Pull request closed without merging**
