### PR TITLE
[NEW] Edited message indicator

### LINKED ISSUE #1133: [NEW] Show edit icon for edited messages
## Description

All messages which are edited should show the icon to indicate that message is edited.

### PR DESCRIPTION
**Pull request by divyanshub024**
@RocketChat/android

Closes #1133 

This PR show "(edited)" on edited messages

edit-indicator

### CODE REVIEW

**Comment by rafaelks** [comment]
@divyanshub024 Do you mind posting a screenshot? Your PR didn't generate the APK for some reason.

**Comment by leonardoaramaki** [comment]
I'd prefer to just show an `(edited)` on the message header rather than any icon. This way is going to be less noisy and I think more performant (one indicator less to render). Can you do this way @divyanshub024?

**Comment by divyanshub024** [comment]
I think it's a great idea, the edit icon wasn't looking good for me.

**Comment by divyanshub024** [comment]
@rafaelks @leonardoaramaki have a look at it.

**Review by leonardoaramaki — APPROVED** [review]

**Comment by leonardoaramaki** [comment]
Thanks!

**Pull request merged**
