### PR TITLE
[WIP][NEW] React to "Share" (ACTION_SEND) intent from another app

### LINKED ISSUE #98: [NEW] React to "Share" (ACTION_SEND) intent from another app
slice

### PR DESCRIPTION
**Pull request by Adizbek**
@RocketChat/android

Closes #98

#### Screenshots or GIF for the change:
https://youtu.be/OsXs4rdySFU

### CODE REVIEW

**Comment by Adizbek** [comment]
I have not finished yet.

**Comment by philipbrito** [comment]
@Adizbek In that case, just add a [WIP] on the PR's title to keeps us informed that it isn't ready to be merged yet.

Thanks for sending it!

**Comment by philipbrito** [comment]
@Adizbek Is it still a WIP?

**Comment by Adizbek** [comment]
@filipedelimabrito Not yet. I let you know when I finish. I have to test it fully.

**Comment by philipbrito** [comment]
Just ping me when it is done and/or remove the [WIP] from the title.
Thank you very much.

**Comment by martinszy** [comment]
Hey, just to encourage you to finish this feature. It's been in the pipeline for three years now and it's one of the main things holding a part of my team from moving to free software messaging.
Thanks for your work :)

**Comment by Adizbek** [comment]
Thanks, I will finish I soon as I finish my final exams, they are sticking for now :sweat_smile:

**Comment by philipbrito** [comment]
@Adizbek Will you be able to work on it?

**Comment by bizzbyster** [comment]
@Adizbek any luck on this? Let me know if you need any help and perhaps we can find someone to finish this up.

**Comment by Adizbek** [comment]
Hello, I apologise, I was on vacation, I will continue this PR.

**Comment by philipbrito** [comment]
Thanks for letting us know @Adizbek! Just ping me here when you think it is done.
Hope you are having a great vacation!

**Comment by leonn** [comment]
Hey, @Adizbek  if you don't mind, I have done the same thing with some improvements, as there are many people wanting & waiting for this behavior to be available,  can I submit a PR to address this ?

**Comment by andrew-thought** [comment]
Would like to see this feature, very important

**Comment by andrew-thought** [comment]
> Hey, @Adizbek if you don't mind, I have done the same thing with some improvements, as there are many people wanting & waiting for this behavior to be available, can I submit a PR to address this ?

I'm very interested leonn, thanks!

**Comment by Adizbek** [comment]
@leonn, of course, I had no time to finish it. It would be great if you have complete this feature, as many people waiting for it.

**Pull request closed without merging**
