### PR TITLE
Make the app list the rooms on login

### PR DESCRIPTION
**Pull request by laggedHero**
- The app is now listing rooms you already have from you user
- Android dependencies updated
- Initial work on make real-time message work

### CODE REVIEW

**Comment by laggedHero** [comment]
:/
I'll check the build tomorrow.

**Comment by cescgie** [comment]
is there any news about this version?

**Comment by YusukeIwaki** [comment]
@laggedHero Thank you for your PullRequest! I will check it soon.

**Comment by YusukeIwaki** [comment]
**AWESOME!!**

**Comment by YusukeIwaki** [comment]
Circle CI is now fixed manually

**Pull request merged**
