### PR TITLE
[BUG] Fixes Drawing cleared on orientation change issue

### LINKED ISSUE #2027: [BUG]  Drawing is cleared on Orientation change.
## Describe the bug
Drawing is cleared on rotating the phone.

## To Reproduce
1. Go to Drawing
2. Draw something on canvas
3. rotate the phone
4. See that drawing is cleared and fresh white canvas appears

## Expected behavior
The drawing should persist on rotation and should not be cleared.

## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

Mobile device model and OS version: ( "Redmi note 5 - Android 8.1.0")

### PR DESCRIPTION
**Pull request by Cool-fire**
@RocketChat/android

 Closes #2027 

#### Screenshots or GIF for the change:
draw

### CODE REVIEW

**Comment by Cool-fire** [comment]
The correct way of approaching this issue would be creating parcelable class for drawing and saving the state before orientation change and restoring after orientation change.

**Comment by Cool-fire** [comment]
@divyanshub024 @rafaelks @filipedelimabrito please review this pull request.

**Comment by divyanshub024** [comment]
@Cool-fire I don't think that this is the best way. Check [
Handle configuration changes](https://developer.android.com/guide/topics/resources/runtime-changes).
It says....
`
Caution: Handling the configuration change yourself can make it much more difficult to use alternative resources, because the system does not automatically apply them for you. This technique should be considered a last resort when you must avoid restarts due to a configuration change and is not recommended for most applications.
`

**Comment by Cool-fire** [comment]
I totally agree with your point @divyanshub024 as I mentioned earlier the solution would be creating a parcelable class.
This would be rather a hack than actual solution.

**Review by philipbrito — APPROVED** [review]
Thank you very much for sending this PR @Cool-fire!

**Pull request merged**
