### PR TITLE
[IMPROVEMENT] Better RU localization

### PR DESCRIPTION
**Pull request by twi123**
@RocketChat/android

1. Fix missing "Done" button (now it can be localized)
2. More correct RU localization

### CODE REVIEW

**Comment by luciofm** [comment]
@twi123 thanks for the PR. You need to rebase your PR against `develop` branch and sign the CLA

**Comment by twi123** [comment]
I've signed CLA
PR rebased to `develop`

**Comment by luciofm** [comment]
@twi123 can you please add the string done in english to other languages with a TODO comment, like:
`<string name="dialog_button_done">Done</string> <!-- TODO Add translation -->`

That way your PR will pass on our automated checks.

**Comment by luciofm** [comment]
Thanks @twi123, did a rebase and squash and merge manually. Thank you again

**Pull request closed without merging**
