### PR TITLE
Edit message support

### PR DESCRIPTION
**Pull request by laggedHero**
@RocketChat/android

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Have you figured out how you're gonna make the edit UI look?

**Comment by laggedHero** [comment]
Working on it. Need to fix some bugs. :/

**Comment by geekgonecrazy** [comment]
I like the start you have! :grin: only complaint is the touch area.  Looks like you have to click the timestamp almost, instinctively I long pressed the text its self expecting that to do something.

**Comment by laggedHero** [comment]
@geekgonecrazy That was one of the bugs.
xD

Not my best work here; but I'm running out of time.

**Pull request merged**
