### PR TITLE
[IMPROVEMENT] Draft messages

### LINKED ISSUE #1917: [NEW] Missing draft feature.
The draft feature was remove on the 3.2.0 app release. We should re-add that feature while making sure that it has no bug (like mentioned internally).

### PR DESCRIPTION
**Pull request by philipbrito**
Closes #1917

### CODE REVIEW

**Review by rafaelks — CHANGES_REQUESTED** [review]
I'm getting a crash here when:

1. Enter in a channel without draft;
2. Enter some text;
3. Tap back;
4. Enter on the same channel;
5. The app crashes.

**Comment by philipbrito** [comment]
@rafaelks Tried here but I'm unable to get the crash.
Could you try it with an empty installation?

**Comment by rafaelks** [comment]
@filipedelimabrito Still crashes, here's the stack trace:

```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{chat.rocket.android/chat.rocket.android.chatroom.ui.ChatRoomActivity}: kotlin.UninitializedPropertyAccessException: lateinit property unfinishedMessageKey has not been initialized

Caused by kotlin.UninitializedPropertyAccessExceptionlateinit property unfinishedMessageKey has not been initialized

Caused by kotlin.UninitializedPropertyAccessException: lateinit property unfinishedMessageKey has not been initialized
       at chat.rocket.android.chatroom.presentation.ChatRoomPresenter.getUnfinishedMessage(ChatRoomPresenter.kt:1314)
       at chat.rocket.android.chatroom.ui.ChatRoomFragment.getUnfinishedMessage(ChatRoomFragment.kt:956)
       at chat.rocket.android.chatroom.ui.ChatRoomFragment.onViewCreated(ChatRoomFragment.kt:244)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
       at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
       at android.app.Activity.performStart(Activity.java:6296)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2544)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2647)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5763)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by philipbrito** [comment]
@rafaelks Let's discuss internally (this is - always - the best to do with situations like that). I am still unable to get the cash 🤔 
Thank you.

**Review by rafaelks — APPROVED** [review]
Perfect! 👌

**Pull request merged**
