### PR TITLE
[i18n] Ukrainian translation file.

### PR DESCRIPTION
**Pull request by philipbrito**
Closes https://github.com/RocketChat/Rocket.Chat.Android/issues/1197

### CODE REVIEW

**Comment by CrimsonAndrew** [comment]
I can see only English texts. Could you add current Ukrainian translation? It's much more easy to correct current mistakes than translate again.

**Comment by philipbrito** [comment]
Hi @CrimsonAndrew, as you requested I created the xml file to you.
Like another contributors requests, we create the xml file with English translation and they translated it.
Unfortunately I can not translate all the file to you.

**Comment by CrimsonAndrew** [comment]
You dont understand, or maybe I didn't explain. You already have Ukrainian translation in Rocket chat. I just want to correct the mistakes. Or maybe I dont understand how it,works
--
从Mail.Ru的Android专用app所发送 星期三, 09 五月 2018, 08:29下午 +08:00 发件人 Filipe de Lima Brito  notifications@github.com :

**Comment by philipbrito** [comment]
Prior to this PR there is no Ukrainian translation in this Rocket Chat application. After this merge we are supporting the Ukrainian translation.

Currently, we support:

- English;
- Portuguese;
- French;
- Hindi;
- Spanish; and now,
- Ukrainian.

For your request, you just have to add the translation for Ukrainian language [here](https://github.com/RocketChat/Rocket.Chat.Android/blob/develop/app/src/main/res/values-uk-rUA/strings.xml).
Can you understand now?

**Comment by CrimsonAndrew** [comment]
50/50. I am using Ukrainian version on PC just now. So all this time I was talking about PC version. Now I see the difference, So now the question is who is responsible for PC version of Rocket?

**Comment by philipbrito** [comment]
Yes, looks like you have done a mistake. 
Are you using the desktop version? If yes, take a look at [this project](https://github.com/RocketChat/Rocket.Chat.Electron).
Are you using the web app version? If yes, take a look at [this project](https://github.com/RocketChat/Rocket.Chat).

But, let me know if you have plans to translate the file to Ukrainian language **for this app**.

**Comment by philipbrito** [comment]
@CrimsonAndrew Are you planning to add the proper translations?

**Comment by CrimsonAndrew** [comment]
No, sorry, I will edit translation for PC version.


>Среда, 16 мая 2018, 4:42 +08:00 от Filipe de Lima Brito <notifications@github.com>:
>
>@CrimsonAndrew Are you planning to add the proper translations?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С наилучшими пожеланиями,
Евгений

**Comment by philipbrito** [comment]
Please, next time, specify/care about the proper repository when opening an issue. It makes everyone (even you) to don't waste time.

Thanks for comprehension.

**Pull request merged**
