### PR TITLE
[WIP][NEW] Redesign onboarding

### LINKED ISSUE #1454: [NEW] Redesign Onboarding
screen shot 2018-07-09 at 11 15 45
screen shot 2018-07-09 at 11 15 52

### PR DESCRIPTION
**Pull request by divyanshub024**
@RocketChat/android

Closes #1454 
## Todo
- [x] Show menu in the toolbar for "terms and service" and privacy policy.
- [x] Fix rocket.chat icon being draw incorrect on the on boarding screen.
- [ ] Smooth dropdown/fade in animation 
- [ ] Change the overflow icon color to white.
- [ ] Update loading view.
- [ ] Remove unneeded code on Activity.
- [x] Remove the use of dialog when changing from https to http for better UX
- [ ] Up views when user starts typing over an EditText.
- [ ] Change fragment transition animation to follow our internal "prototype".
- [x] Bold some part of the texts on LoginOptions view. 
- [ ] Update icons on "Login with e-mail".
- [ ] Add again the login with Wordpress Com.
- [ ] Add again the login with Wordpress Custom OAuth.
- [ ] Add again the login with Custom OAuth.
- [ ] Add again the login with CAS
- [ ] Add again the login with SAML
- [ ] Fix broken deep link

## Screenshots
To be updated soon.

### CODE REVIEW

**Comment by rafaelks** [comment]
@divyanshub024 Looking good! 👊

**Comment by philipbrito** [comment]
@divyanshub024 When working with the `3.0.0` version lets add the commits into the `v.3.0.0` branch. 
I did that for this PR. 
Thanks

**Review by philipbrito — CHANGES_REQUESTED** [review]
What I quickly see from your screenshots is that it is showing the `Connect with a server` message two times. For the bluer button you must show the `Create a new server` message instead.

**Comment by divyanshub024** [comment]
@filipedelimabrito I have updated few screens. Still some more work to do.

**Review by philipbrito — CHANGES_REQUESTED** [review]
The key icon (shown in the login and sign up screen) is with a wrong rotation . I'll provide that icon to you soon 👍

**Comment by philipbrito** [comment]
@divyanshub024 Could you please indicate in the PR what tweaks need to be done here (as we talk privately)?

Also, there are conflicts on your PR, could you fix then too? 

Thanks.

**Pull request closed without merging**
