### PR TITLE
[BUG] Fix alert dialog Button

### LINKED ISSUE #1990: [BUG] Alert button not showing title.
screenshot_20190111-113734

### PR DESCRIPTION
**Pull request by divyanshub024**
@RocketChat/android

Closes #1990

#### Changes:
Use `androidx.appcompat.app.AlertDialog` class rather than `android.app.AlertDialog`.

### CODE REVIEW

**Review by philipbrito — APPROVED** [review]
I have fixed some wrong formatting here 👍 
Thank you very much for this PR @divyanshub024 💯

**Review by GOVINDDIXIT — COMMENTED** [review]
LGTM!! 👍

**Comment by divyanshub024** [comment]
@filipedelimabrito What's the code style you guys are using? For me, tab size: 4, indent: 4 and continuation indent: 8

**Comment by philipbrito** [comment]
@divyanshub024 This one: https://github.com/RocketChat/Rocket.Chat.Android#coding-style

**Pull request merged**
