### PR TITLE
[IMPROVEMENT] networkSecurityConfig for API 24+ to allow user imported root CAs as trust anchors

### LINKED ISSUE #793: [NEW] Cannot connect to TLS protected servers with non-public CA signed certificate
Your Rocket.Chat.Android version: 1.1.0

Mobile device model and OS version: Nexus 6 - Android 7.1.1

Reproduction:
1) Create a private CA (common for internal organization applications)
2) Import the new Root CA certificate as a trusted User CA
2a) Settings->Security->Install From Storage
2b) Verify: Settings->Security->Trusted Credentials->User
3) Sign and install a certificate on an internal RockerChat server
4) Connect to the internal RocketChat server

Expected behavior: 
the connection succeeds.

Actual Behavior:
"There's a connection error. Please try again later."
packet capture shows a TLS connection is initiated, Client Hello succeeds, Server Hello succeeds, Server certificate is presented, then the client responds with "Fatal Alert, Certificate Unknown"

This can be reproduced with multiple certs/servers, the same certs work from the native Android browser on the same device, the same certs work form the Cordova version on the same device. The same install of Rocket.Chat.Android works for public RocketChat instances signed with certificate from a public CA.

### PR DESCRIPTION
**Pull request by robertwessen**
@RocketChat/android

Closes #793

Add networkSecurityConfig settings to allow trusted root CAs which have been imported explicitly by the user. This mirrors the default behavior of all apps before API 23, however with API 24 and above this must be set explicitly per app. This is important for internal organization deployments of RocketChat which use TLS, as their certs will most likely not be signed by a public CA from the default Android system truststore.

### CODE REVIEW

**Comment by rafaelks** [comment]
@robertwessen Thank you for the PR, we'll be reviewing it soon.

**Comment by pfunk1978** [comment]
@rafaelks Is it possible to get this into 2.0.1?

**Comment by rafaelks** [comment]
This PR looks good to me! IMHO we can include this one on 2.0.0. Thank you @robertwessen! 👍

**Comment by pfunk1978** [comment]
Thank You!

**Pull request merged**
