### PR TITLE
Fix 247 change hostname

### LINKED ISSUE #247: Cannot set hostname
Your Rocket.Chat.Android version: 1.0.8

Updated to 1.0.8 Android. I did have previous version working, now I need to point this updared app at a new RC server.

The app does not display the screen to set hostname, only shows login screen.

I have uninstalled and reinstalled, still do not see the hostname interface on startup

### PR DESCRIPTION
**Pull request by aenonGit**
@RocketChat/android

Starting Point to FIX: #247 

Notes
As suggested by @geekgonecrazy I'm Opening the PR to try to fix the above issue.
I'm not satisfied with such solution, yet it is a good starting point IMHO.

There are also other paths that can be followed:

1. clear/drop the Realm DB to remove everything from the previous session (rooms, messages, ...)

2. clear the RocketChatCache (selected RoomID, ServerHostname, RoomIdPublisher, ...)

There are still other issue, maybe or maybe not related to this one:

- (not completely replicable): after some tests, something breaks in the RocketChatCache leading to a crash;
- After logout/remove server it keeps receiving notification from the server. 
This happens in these scenarios: 1) logout/remove server (without login again); 2) logout/remove server (login to another server). It does not happen in this scenario: logout/remove server (login to the same server but with another user).

### CODE REVIEW

**Comment by rafaelks** [comment]
@matheusjardimb Can you please review this PR?

**Comment by matheusjardimb** [comment]
Hello @aenonGit! Thanks for your support trying to fix our issues. ;)
Unfortunately I believe there's still some more changes to be done before accepting this PR. 

I've downloaded this PR and there's a crash I can easily reproduce:

- login into server A
- logout
- login into server B
- logout = crash

Would you please investigate this scenario before we can proceed merging?

**Comment by aenonGit** [comment]
Hi @matheusjardimb, this PR was never meant to be merged, It's just a starting point to fix the issue. The crash you experience is the one I've described in the above note (localized in the RocketChatCache.java class). I'll keep working on it, as well as I hope someone else will.

The primary goal was to get help from the community, since the code is not very well "understandable".

**Comment by aenonGit** [comment]
@matheusjardimb would you please give it a try?

**Comment by matheusjardimb** [comment]
@aenonGit Sure!

**Comment by aenonGit** [comment]
@matheusjardimb any news?

**Comment by matheusjardimb** [comment]
Sorry @aenonGit about the delay. I've tested this PR and the chrash seemed to get fixed. Yay! 
Thanks for your help, I'm merging this!

**Review by matheusjardimb — APPROVED** [review]

**Comment by rafaelks** [comment]
@aenonGit Thank you!

**Pull request merged**
