### PR TITLE
[I18N] Update strings

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
@RocketChat/android

For #1918

### CODE REVIEW

**Comment by GOVINDDIXIT** [comment]
@cmassi pls review italian changes

**Review by cmassi — CHANGES_REQUESTED** [review]
I would update app/src/main/res/values-it/strings.xml with

    <string name="msg_team_communication">Comunicazione dei Gruppi</string>

    <string name="msg_unable_to_update_password">Impossibile aggiornare la password. Messaggio di errore: %1$s</string>
    <string name="msg_password_updated_successfully">Password aggiornata con successo</string>

**Comment by GOVINDDIXIT** [comment]
Thanks @cmassi  will you send a PR ? or I should do these change in this PR only

**Comment by filipedelimabrito** [comment]
@GOVINDDIXIT Let's avoid the use of a translator service. Could you translate only the file of your mother language here, please?

**Review by philipbrito — CHANGES_REQUESTED** [review]
@GOVINDDIXIT Let's avoid the use of a translator service. Could you translate only the file of your mother language here, please?

**Comment by GOVINDDIXIT** [comment]
Sure @filipedelimabrito I will remove other files

**Comment by GOVINDDIXIT** [comment]
@filipedelimabrito done! Pls review

**Review by philipbrito — APPROVED** [review]
Thank you very much @GOVINDDIXIT! 🎉

**Pull request merged**
