### PR TITLE
[NEW] Add erase feature in drawing

### LINKED ISSUE #1938: [NEW] Add erase feature in Drawing
## Description

Right now in draw the erase will clear the whole canvas. This feature will erase only the respective area where you touch.

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
Closes #1938 #2021 https://github.com/RocketChat/Rocket.Chat.Android/pull/2022

### New Features
On Clicking eraser widget you can erase from the canvas
On long pressing the eraser widget the whole canvas got cleared
Also, the size of eraser can be increased/decreased using stroke width

### Bug Fixes
Not able to select black color in color pallete

### GIF
gif-181225_165520
### New GIF
gif-190118_212728

### CODE REVIEW

**Comment by GOVINDDIXIT** [comment]
@filipedelimabrito @rafaelks  pls review

**Review by philipbrito — APPROVED** [review]
Good one @GOVINDDIXIT! Thanks for sending this PR!

**Review by divyanshub024 — APPROVED** [review]
LGTM 👍

**Review by philipbrito — CHANGES_REQUESTED** [review]
I have fixed some formatting issues here (check out our [coding style](https://github.com/RocketChat/Rocket.Chat.Android#coding-style) for future reference).

There is a bug: When the user clear the canvas (long pressing the erase button) the redo button doesn't work properly (try tapping the undo and redo bottom after clearing the canvas). Could you check that @GOVINDDIXIT ?

**Comment by GOVINDDIXIT** [comment]
Sure, I will check and push changes soon

**Comment by GOVINDDIXIT** [comment]
@filipedelimabrito updated. Pls review. I have also posted the new GIF

**Comment by GOVINDDIXIT** [comment]
Updated @filipedelimabrito  Pls review

**Review by philipbrito — APPROVED** [review]
Thank you @GOVINDDIXIT!
💯

**Pull request merged**
