### PR TITLE
[NEW][WIP] Implement FOSS build flavour

### LINKED ISSUE #26: [REQUEST] Upload the app to F-DROID
Hello,

As the licence (MIT) is compatible with the FOSS catalog "F-DROID", is it possible to get the app there ?
I am a Rocket.Chat user on my desktop browser, but on my mobile browser it is not easy to use. Moreover, I have uninstalled Google Play Store, and thus won't get the app on it.

Thanks in advance

### PR DESCRIPTION
**Pull request by Bubu**
@RocketChat/android

Closes #26 

Provide two build flavours 'Foss' and 'Play', the 'Play' flavour is
unchanged to what we had beforae. The 'Foss' flavour removes the
dependence on proprietary libraries.

This removes crashlytics, instead logging to the local log.

It also removes firebase/gcm messaging, disabling push functionality.
For now there is no replacement for this.

### CODE REVIEW

**Comment by Bubu** [comment]
The CI failures show an interesting problem...
It's running `./gradlew assembleRelease` and apparently failing on:
```
* What went wrong:
Execution failed for task ':app:kaptPlayReleaseKotlin'
```

I can reproduce this locally. **But** running `./gradlew :app:kaptPlayReleaseKotlin'` works. As do `./assemblePlayRelease` and `./gradlew assembleFossRelease`.

This is beginning to sound like a gradle/android gradle plugin/kapt bug? Anyone got any ideas where to start reporting this?

**Comment by Bubu** [comment]
Lint works locally for me, the CI runs seemed to just abort. Maybe someone can retrigger it?

**Comment by rafaelks** [comment]
@Bubu Thank you very much for your PR! We'll be reviewing it very soon. 👍

**Comment by Bubu** [comment]
What about the Codacy errors? Should I fix them? But I think it's probably more productive if you'd take a look first and tell me if I should rename/move around things or do things differently.

**Comment by philipbrito** [comment]
Don't worry about Codacy @Bubu 
We aren't using it but I know that we need to remove it.

**Comment by Bubu** [comment]
Gentle Ping! :-)

Any progress on this?

**Comment by Bubu** [comment]
Forgive me for being impatient but I'd really like to see this in f-droid soon.
Would you be okay to add this PR as a patch on the f-droid side until it's merged here in some form?
I'm using the app built with this applied for > 2 weeks now without problems.

The Description of the app will clearly state that no notifications will be working and this is a restriction on the f-droid build only. (which finding an alternative solution to GCM would be another topic I'd like to discuss at some point.)

**Comment by rafaelks** [comment]
@Bubu I'm sorry for the delay on merging this one, we were preparing to make a release last Friday (and we did) so I guess this week we'll be able to merge it 👍

**Comment by rafaelks** [comment]
@Bubu Can you contact me at `@rafael.kellermann` in our server https://open.rocket.chat? Thank you!

**Review by rafaelks — APPROVED** [review]

**Comment by Bubu** [comment]
Rebased on develop to fix the merge conflicts. The `foss` flavour is not building currently because of the Google Smart Lock integration.

I'll need some more time to see how to solve this.

**Comment by Bubu** [comment]
Marking this as WiP. I began with moving the google smart lock stuff into the play flavour, MainActivity is done, still need to go through all the Login/Signup View/Fragments/Presenters,

**Comment by vynmera** [comment]
Any update? I need this as I do not have GApps (and do not intend to ever install them thanks)

**Comment by rafaelks** [comment]
@vynmera We'll be resolving this one very soon and the FOSS will be automatically generated in future versions. 👍

**Comment by beranPro** [comment]
+1

**Comment by vynmera** [comment]
When can we expect to see this on F-Droid?

**Comment by Bubu** [comment]
> When can we expect to see this on F-Droid?

In a few days.

**Pull request closed without merging**
