### PR TITLE
[FIX] Typo in VersionCheckView.kt

### PR DESCRIPTION
**Pull request by noor-binte-amir**
@RocketChat/android

#### Changes:
Corrected sentence.

#### Screenshots or GIF for the change:
6 error3

### CODE REVIEW

**Comment by GOVINDDIXIT** [comment]
@NBAMIR I think sending separate PRs for typo fix in each file is not good when you can do all of the fixes in one PR. Hope you understand.

**Comment by noor-binte-amir** [comment]
Hi, I don't have previous experience with open source contribution so I'm trying to get the hang of it. Any suggestions or advice is welcome. I didn't know I could commit fixes in different files in one PR. Thanks for the heads up.

**Comment by GOVINDDIXIT** [comment]
@NBAMIR  This will help https://stackoverflow.com/questions/19576116/how-to-add-multiple-files-to-git-at-the-same-time.  You can also look at official documentation of git to learn more about it[ here](https://git-scm.com/doc)

**Comment by noor-binte-amir** [comment]
Thank you for the suggestion. I'll check it out.

**Review by philipbrito — COMMENTED** [review]
Thanks for sending this PR @NBAMIR

**Pull request merged**
