### PR TITLE
Fix about fragment title on rotate

### LINKED ISSUE #2063: [BUG] About fragment app bar title is change from "About" to "Rocket.Chat" on rotate.

### PR DESCRIPTION
**Pull request by arthurbdiniz**
Signed-off-by: Arthur Diniz <arthurbdiniz@gmail.com>

@RocketChat/android

Closes #2063

### CODE REVIEW

**Comment by dev-ritik** [comment]
@arthurbdiniz this is not the correct way to handle this.
As mentioned [here](https://developer.android.com/guide/topics/resources/runtime-changes),
`Caution: Handling the configuration change yourself can make it much more difficult to use alternative resources, because the system does not automatically apply them for you. This technique should be considered a last resort when you must avoid restarts due to a configuration change and is not recommended for most applications.`

**Comment by arthurbdiniz** [comment]
Hi @dev-ritik, thanks for the reply, i will fix this.

**Comment by arthurbdiniz** [comment]
Just update the code with a more common solution

**Comment by philipbrito** [comment]
@arthurbdiniz, thanks for sending this PR but this one sent one day ago before your change already fixes it: https://github.com/RocketChat/Rocket.Chat.Android/pull/2092

**Pull request closed without merging**
