### PR TITLE
Basic Project

### PR DESCRIPTION
**Pull request by BugsBunnyBR**
Hi, this is a very basic project, but I think it may be a starting point. It is using DDP protocol under the hood and I modified a classic java implementation of Meteor to work with OkHttp-ws instead of the Android autobahn (which it is not being updated ) to make it more robust;
I want, at some time in the future, to separate the operations/models packages into a different project to make a library of it.

What the app already does.
- Login with default (email/username)/password;
- Registration of a new user;
- List the last 50 messages from GENERAL room;
- If you click in the "search" icon in the bar in the top, you will hit the server and filter the messages by "teste" string;

The implementation of the Android code is rather simple at the moment, in this first step I would like to see how things that I don't know work, i.e., the Meteor protocol and the RC data flow.

Can I see it working?
Yes, you can download the apk (inside RocketChat/app folder) and see it working by yourself.
That is all folks.

### CODE REVIEW

**Comment by YusukeIwaki** [comment]
Hey, I'm also trying to create Rocket.Chat android native app.

As you wrote, DDP client libs for Android currently known (such as Android-DDP, android_ddp_client) are not maintained enough.
I think it is better to make our own DDP client which is convenient just for Rocket.Chat, because DDP  is very simple protocol to implement. (In my implimentation, just [this](https://github.com/yi01/Rocket.Chat.Android/blob/8f1699bdaa9aa7b9ca849a118e88379db9d98d5e/android-meteor/src/main/java/jp/co/crowdworks/android_meteor/ddp/DDPClientImpl.java) )

Your repository currently has 'database' named branch. Do you intend to implement the app with the  component structure as below?
slice 1
(if so, I will be able to contribute actively! :laughing: )

Could you share the abstract design of this application if possible?
Thank you!

**Comment by BugsBunnyBR** [comment]
@YusukeIwaki , Hi, I did see your repo early this week and it is very nice to know someone else want to build a native Rocket Chat (RC) client. (I would have created an issue if that was enabled...)

I don't know if I have an abstract design, I don't think I thought too much about it, but yeah I intent to use a model just like yours. The RC client writes into the database and the Activity/Fragment access the database using  ContentProvider/ContentObserver to get a Cursor.

At the moment I am trying to build the app in a way that the meteor part is pure java, so I can make it a module to use in desktop/server apps, so I am not using the Reactive approach or referencing any Context/Android related resource. I did not created the meteor library from scratch as you, I just made a few fixes to Android-DDP and migrated to OkHttp-ws and Gson. I think it would not be hard to create a reactive module from it, but it is not in my plans for now. (Even though I see it would be a better way to be done from the very beginning as you are doing).

I'm still experimenting to see what pleases me while coding and any help would be nice. I am a total n00b in DDP/Meteor/RC so I am trying to understand how the chat should work to afterwards improve my implementation.

I need to push some code to that database branch, but I have some security concerns that I need to address about a possible Twitter login integration (I forgot to create another branch :-P ). If you want to talk, look for me in the Rocket Chat demo.rocket.chat, my user is julio.cesar.bueno.cotta, we can talk in the androidnativeapp or in pvt.

**Comment by BugsBunnyBR** [comment]
- separated the project into some modules (app, rc, meteor, rxrc, rxmeteor, timber*); The "rx" ones are Android reactive modules, the other ones plain java modules. \o/
- Login with Facebook;
- Send/receive text  messages;
- Push notifications;
- Created a nice right menu in chat screen;
- Created a screen to record audio, but the upload it not working yet;
- updated the APK in the app folder of master branch; 

*timber is a log library for Android, but with few modifications it now logs everywhere.

**Comment by yi01** [comment]
> Created a screen to record audio, but the upload it not working yet;

@BugsBunnyBR:
I managed to find that uploading file may be accomplished by passing "_id" parameter to  the "rocketchat_uploads/insert" method call for registering fileID to use with ufsWrite/ufsComplete methods.

https://github.com/yi01/Rocket.Chat.Android/commit/621f6b2cbd34cce06ef43bddb3ee246869f1f0ce

Please try it if you like!

**Comment by BugsBunnyBR** [comment]
@yi01, thanks for the tip, I got it working too after some talk with one of Rocket team members he pointed that to me too. Did you get to record audio in wav? After some research I understood that html5 audio player (in the web client) does not play mp4/3gp audio formats that are more easily recorded on Android using MediaRecord. To get wav format we need to use AudioRecord and start pooling the audio output...which is not ideal. I will give AudioRecord a try tonight...

**Comment by YusukeIwaki** [comment]
```
12-09 10:52:35.193 E/AndroidRuntime( 2481): Process: chat.rocket.app, PID: 2481
12-09 10:52:35.193 E/AndroidRuntime( 2481): java.lang.NoClassDefFoundError: Failed resolution of: Lchat/rocket/app/db/dao/RcSubscriptionDAO;
12-09 10:52:35.193 E/AndroidRuntime( 2481): 	at chat.rocket.app.db.SQLiteHelper.onCreate(SQLiteHelper.java:73)
12-09 10:52:35.193 E/AndroidRuntime( 2481): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
12-09 10:52:35.193 E/AndroidRuntime( 2481): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
```

I can't try this app...

**Comment by BugsBunnyBR** [comment]
I will take a look at it right now

**Comment by BugsBunnyBR** [comment]
@yi01 , I think you should try to compile again, the class is in the repository (https://github.com/BugsBunnyBR/Rocket.Chat.Android/blob/master/RocketChat/app/src/main/java/chat/rocket/app/db/dao/RcSubscriptionDAO.java). Give it a "clean" and "assembleDebug" again.

I just pushed the audio recording feature with wav support, give it a pull to get the latest code.

**Comment by YusukeIwaki** [comment]
@BugsBunnyBR Thank you for your kind help!

**Comment by sampaiodiego** [comment]
@RocketChat/core anyone have seen this? why is it not merged?
looks a lot of work, btw
good work @BugsBunnyBR :smile:

**Comment by engelgabriel** [comment]
Strange! I didn't get any alerts for this! :(

Let's merge it!

**Comment by engelgabriel** [comment]
Should we move all this information to the wiki?

**Comment by engelgabriel** [comment]
And mr @BugsBunnyBR I've added you to the team, so no you have commit rights to the official repo, so you can create your branches and PRs here directly. :)

**Comment by BugsBunnyBR** [comment]
\o/ thanks doc!

**Comment by graywolf336** [comment]
:+1: looking good!

**Pull request merged**
