### PR TITLE
[IMPROVEMENT] Show users summary when long-clicking reaction

### LINKED ISSUE #919: [IMPROVEMENT] Show users when long pressing a reaction

### PR DESCRIPTION
**Pull request by Tunous**
@RocketChat/android

Closes #919 

This PR adds a long press action to chat message reactions. It allows users to view summary of people who have reacted with the clicked emoji.

___

The code for creating summary text has been based on [this block of code](https://github.com/RocketChat/Rocket.Chat/blob/dbff6ee20ff756d5654bc36da66de4999ff7cd9c/packages/rocketchat-ui-message/client/message.js#L224). Also the translations were based on files located [here](https://github.com/RocketChat/Rocket.Chat/tree/master/packages/rocketchat-i18n/i18n). Unfortunately I **did not manage to find translations for Hindi** (hi-lIN) here so these are missing in my PR.

### CODE REVIEW

**Comment by leonardoaramaki** [comment]
Thanks for your contribution! 
Have you tested how it looks when many users give the same reaction?
I think some sort of dialog would look better.

**Comment by Tunous** [comment]
It's limited to displaying first 15 users so it looks similar to mouse over popup in web version. 
I could try coming up with some sort of dialog if that's preferred. Decision is up to the team.

**Comment by leonardoaramaki** [comment]
@Tunous Any news on the UX? Have you made any changes to the UI or are you going to leave it as it is?

**Comment by Tunous** [comment]
Sorry, I've forgotten about this pull request.

I've pushed a new commit which modifies the interface to show a dialog looking like this:

screenshot_1541437595

_NOTE: Newly added string is not translated to other languages as I can't speak them._

**Comment by leonardoaramaki** [comment]
Thanks for this contributions @Tunous!

**Review by leonardoaramaki — APPROVED** [review]

**Pull request merged**
