### PR TITLE
[FIX] Chat list scrolls down when a new message arrives in a channel

### LINKED ISSUE #791: [FIX] Chat list scrolls down when a new message arrives in a channel.
Even on top of the list (I men, seeing the first channel on the screen) the chat list scrolls down when a new message arrives in a channel.

### PR DESCRIPTION
**Pull request by harisankerPradeep**
The bug was that when a new message pops up in the channel the list scrolls down. To fix this the line
```
        recycler_view.scrollToPosition(0)
```
was commented. However, further modifications will be needed, like a toast, to notify the user of the new message. Would love to work on the same if deemed necessary by the community. 

Closes #791,
Thanks in advance!

### CODE REVIEW

**Comment by harisankerPradeep** [comment]
CircleCI tests show : 
```
Your build has exceeded the memory limit of 4G on 1 container. The results of this build are likely invalid. We have taken a snapshot of the memory usage at the time, which you can find in a build artifact named `memory-usage.txt`. The RSS column in this file shows the amount of memory used by each process, measured in kilobytes.
```

How should I proceed? 

Thanks in advance!

**Comment by rafaelks** [comment]
@harisankerPradeep Could you please resolve the conflicts?

**Comment by harisankerPradeep** [comment]
@rafaelks it's done

**Comment by rafaelks** [comment]
@harisankerPradeep I'm sorry the delay again... can you fix the conflicts now? I do plan to merge this PR now.

**Comment by philipbrito** [comment]
Closing this PR because it has some conflicts unsolved and this was already fixed in the current version.
Thank you.

**Pull request closed without merging**
