### PR TITLE
[NEW] Unpin message from PinnedMessageActivity

### LINKED ISSUE #852: [New] [UX] There should be an option to unpin the pinned messages from "Pinned Message" activity
**Rocket.Chat.Android version:**
versionCode 1009
versionName "2.0.0-dev7"

# Description
Option to unpin the messages pinned by you is not there in pinned message activity.

**Willing to work on it?** YES

### PR DESCRIPTION
**Pull request by divyanshub024**
@RocketChat/android

Closes #852

### Description
This PR allows you to unpin the pinned Message from PinnedMessageActivity
OnLongClick on the pinned message the alertDialog will ask you to unpin the message.

device-2018-03-13-140448

### CODE REVIEW

**Comment by rafaelks** [comment]
@divyanshub024 Thank you for your PR! I believe we can show all the actions we're showing today on the messages list, instead of just this alert. What do you think?

**Comment by divyanshub024** [comment]
@rafaelks I didn't get it. By this, you mean that every message should have an icon to unpin?

**Comment by divyanshub024** [comment]
I also want to know why the circleci test failed?

**Comment by mmarif4u** [comment]
I guess what @rafaelks means is the context menu appear by long holding on the message which have different actions like Delete, pin message etc etc.

**Comment by rafaelks** [comment]
@divyanshub024 Exactly what @mmarif4u said.

**Comment by divyanshub024** [comment]
@rafaelks @mmarif4u In PinnedMessageActivity you don't have actions like delete, pin message etc. PinnedMessageActivty only shows pinned messages.

**Comment by divyanshub024** [comment]
@rafaelks How do you suggest this action to be performed?

**Comment by mmarif4u** [comment]
2 ways to do it, one is to switch the action to either "Pin Message" if it not yet or "Unpin Message" if it is pinned already.

2nd is to leave it as it is what you have implemented so far.

I will leave it to the RC Core team to decide on that.

**Comment by mmarif4u** [comment]
@divyanshub024 you are right, the pinned messages list is different from context menu.

**Comment by divyanshub024** [comment]
@mmarif4u should I leave it for now or should I change it?

**Comment by rafaelks** [comment]
@divyanshub024 You could still implement it... I could reply, copy, quote, unpin and delete a pinned message from the pinned list. In case of reply/quote, you could close the window and call the reply/quote action into the chat activity. What do you think?

**Comment by divyanshub024** [comment]
@rafaelks I think its a great idea. I'll start working on it.

**Comment by divyanshub024** [comment]
clone: #1029

**Pull request closed without merging**
