### PR TITLE
[WIP][CHORE] Update circle.ci config to run UI tests

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
@RocketChat/android

This PR is specific to GSoC'19 project (Improve test automation in Rocket.Chat Android Repo)
#### Changes: 
A new job is added in the workflow to run UI tests

### CODE REVIEW

**Comment by philipbrito** [comment]
@GOVINDDIXIT `run-ui-tests` is not passing. Are you going to fix the error there?

**Comment by GOVINDDIXIT** [comment]
@filipedelimabrito Yes I am working on it, Can you help me in fixing this. The weird part is that the command ./gradlew connectedAndroidTest is working fine in local machine but throwing this error on ci
`e: org.jetbrains.kotlin.util.KotlinFrontEndException: Exception while analyzing expression at (43,44) in /home/circleci/project/app/src/main/java/chat/rocket/android/authentication/registerusername/presentation/RegisterUsernamePresenter.kt`
As suggested online I have tried updating the kotlin version but again it is failing.

**Comment by GOVINDDIXIT** [comment]
@filipedelimabrito I have solved the previous issue, now circle ci is running tests on the emulator but it is facing some memory issue because of which the overall build is failing. Can you pls look into it and suggest some fix?

**Comment by philipbrito** [comment]
@GOVINDDIXIT Please make sure to test it a lot before requesting help for inexistent issues. It is just failing for the `run-ui-tests`

**Comment by GOVINDDIXIT** [comment]
@filipedelimabrito I agree with you but since circle ci provides limited build minutes under the free plan, and I have already used many of it during setting it up and debugging. I will setup the circleci locally maybe it will help in debugging the issue.

**Comment by ear-dev** [comment]
@GOVINDDIXIT Just so I understand please.........  this PR just sets up the emulator but does not run any tests?  Or are there previous UI tests that are configured to run that are not visible in the changes?

**Comment by GOVINDDIXIT** [comment]
@ear-dev the PR setup the emulator and run the UI test (currently only 1 empty tests). As I have mentioned earlier the UI tests of chatroom fragment are currently failing so I had commented them. The tests are running fine on emulator the main problem is to allocate proper memory because of which the whole build is failing. I have looked for all possible solutions and find that we have to increase the memory of Ci to run ui tests

**Comment by philipbrito** [comment]
Closing this one. As talked internally we don't need it for now.

**Pull request closed without merging**
