### PR TITLE
[FIX] Avatar cache bug

### LINKED ISSUE #2040: [BUG] Profile avatar is not changing
## Describe the bug

After chaning the avatar in profile the avatar is set back to previous profile pic. The change is reflected on web but not on android app.
## To Reproduce
1. Go to profile
2. Click on the profile picture and select `Reset avatar` or any other option.
3. Go to chats or some other fragments and come back. 
4. Your previous avatar will there.

## Expected behavior

Same as the web.

## GIF

ezgif-1-dd40f7d3fef8

### PR DESCRIPTION
**Pull request by dev-ritik**
@RocketChat/android

Closes #2040 

#### Changes: Replaces `username` with corresponding imageUri

### CODE REVIEW

**Comment by dev-ritik** [comment]
@divyanshub024 PTAL!

**Comment by rockneverdies55** [comment]
Is this fixing #1217 as well?

**Comment by dev-ritik** [comment]
This PR is all about updating locally cached avatar whenever it is updated by the device itself @rockneverdies55 .
Add I have already started working on #1217 and will soon come up with a PR or a conclusive statement on it.

**Comment by Phr33d0m** [comment]
@dev-ritik thank you very much!! I can confirm that this solved #2040 for me. This does **not** solve #1217 though.

**Review by philipbrito — APPROVED** [review]
Thank you very much for submitting this PR @dev-ritik!

**Pull request merged**
