### PR TITLE
[FEATURE] Implement FOSS build flavour

### LINKED ISSUE #26: [REQUEST] Upload the app to F-DROID
Hello,

As the licence (MIT) is compatible with the FOSS catalog "F-DROID", is it possible to get the app there ?
I am a Rocket.Chat user on my desktop browser, but on my mobile browser it is not easy to use. Moreover, I have uninstalled Google Play Store, and thus won't get the app on it.

Thanks in advance

### PR DESCRIPTION
**Pull request by luciofm**
Based on work from @Bubu https://github.com/RocketChat/Rocket.Chat.Android/pull/1232

Closes #26
Closes #1232

Provide two build flavours 'Foss' and 'Play', the 'Play' flavour is
unchanged to what we had beforae. The 'Foss' flavour removes the
dependence on proprietary libraries.

This removes crashlytics, instead logging to the local log.

It also removes firebase/gcm messaging, disabling push functionality.
For now there is no replacement for this.

TODO:
[ ] - Add ACRA or other crashing report tool for FOSS builds.

### CODE REVIEW

**Comment by rafaelks** [comment]
@Bubu Do you mind signing the CLA here so we can merge the PR please? :-)

**Comment by Bubu** [comment]
Done.

**Review by philipbrito — APPROVED** [review]
Not sure, but is `ActivityKt.kt` a typo?

**Comment by himpierre** [comment]
This is *really* great guys. Thank you. Just compiled develop. Works! :-)

**Comment by martinszy** [comment]
Hello, what are the steps missing for this to be included in the fdroid catalogue?

**Comment by philipbrito** [comment]
There are still some work in progress in the cycle @martinszy. We are planing to ship the new version on the end of this month.

**Comment by martinszy** [comment]
I checked today and it's still not available. Any information on the tasks left for this? Help needed?
Will it be a custom repo or the main fdroid one?
Has it already been submitted for fdroid to verify?

**Comment by rafaelks** [comment]
This is probably going to be released in our next update in Google Play in a few days. Please keep looking here for news, we will certainly update the PR and the issue with more information.

**Pull request merged**
