### PR TITLE
[BUG] Solves the favorite icon not being shown.

### LINKED ISSUE #2165: [BUG] There is no mechanism to add a channel to favorites.
Your Rocket.Chat.Android version: 3.3.0 Build 2059 - 1115477 - play
Mobile device model: Xiaomi Redmi 3
OS version: Lineage OS, Android 7.1.2
Your Rocket.Chat Server version: 0.74.3

In new betas there is no mechanism to add a channel to favorites.

### PR DESCRIPTION
**Pull request by Adizbek**
@RocketChat/android
Closes #2165

#### Screenshots or GIF for the change:
image

### CODE REVIEW

**Comment by Adizbek** [comment]
@filipedelimabrito, I think this PR is safe to merge, just one line code. :)

**Comment by philipbrito** [comment]
@Adizbek I'll test it as soon as possible on the device.

**Review by philipbrito — APPROVED** [review]
Thanks for sending this PR @Adizbek!

**Comment by philipbrito** [comment]
@Adizbek It's solving the https://github.com/RocketChat/Rocket.Chat.Android/issues/2165, but we still have this issue: https://github.com/RocketChat/Rocket.Chat.Android/issues/2234. Just letting you know here :)

**Pull request merged**
