### PR TITLE
Reduce method count

### PR DESCRIPTION
**Pull request by luciofm**
- Remove Fernando Ceja's arrow, we use only Optional and replace for a small library
- use compileOnly for auto-value

### CODE REVIEW

**Comment by luciofm** [comment]
current develop branch: 87221 methods
this branch: 78068 methods

**Comment by filipedelimabrito** [comment]
We only need to fix the CI to merge this PR.

**Review by philipbrito — COMMENTED** [review]
We only need to fix the CI to merge this PR.

**Comment by leonardoaramaki** [comment]
@filipedelimabrito @luciofm The circleci is failing due to an OOM error. I did some changes to circleci.yml on my WIP PR which made it work. Please refer to: https://github.com/RocketChat/Rocket.Chat.Android/blob/9553a57e1cc2b097385babfeda24ea5791b46dc3/circle.yml

**Comment by philipbrito** [comment]
Great @leonardoaramaki ! Anyway, I think is time to decide what CI tool to use. Two is confusing.

**Review by rafaelks — APPROVED** [review]

**Pull request merged**
