### PR TITLE
[NEW] Emoji keyboard

### LINKED ISSUE #722: [NEW] Emoji Keyboard support

### PR DESCRIPTION
**Pull request by leonardoaramaki**
@RocketChat/android

There's much room for improvement that I'll be working on. Anyway this is the first version of our finally awaited emoji keyboard crafted by hand. :)

Closes #722

### CODE REVIEW

**Review by rafaelks — CHANGES_REQUESTED** [review]
@leonardoaramaki Just finished testing the build, here are a few bugs that I found and other things to improve before we merge it:

- When you rotate the screen, it breaks the layout of the sections; Let's just adjust the spacing or fill the color until the end of the view;
- Pressing the Emoji button is very hard (at least for me on my physical device), needs o be easier. Maybe increase the touch area?
- The emoji picker is opening on top of the keyboard? It should use the exactly same space and design as keyboard is using, also showing the text of the user on the top; (Look at this, maybe this is the way to go: a new input method for Emojis: https://developer.android.com/guide/topics/text/creating-input-method.html)
- When I open the picker, if I have at least one recent emoji, the tab selected should be the recent emojis;
- When you get to the end of the list, there are 0px between the bottom of the device and the bottom of the emojis. Let's add at least 16px of space;

**For future PR:**
- Filter same emoji and different colors; Show only one color and user will be able to change the color of all in just one place;

**Comment by leonardoaramaki** [comment]
@rafaelks I'm putting the adjustments here so that we can all keep track of its progress.
- [x] When you rotate the screen, it breaks the layout of the sections; Let's just adjust the spacing or fill the color until the end of the view;
- [x] When I open the picker, if I have at least one recent emoji, the tab selected should be the recent emojis;
- [x] Pressing the Emoji button is very hard (at least for me on my physical device), needs o be easier. Maybe increase the touch area?
- [x] The emoji picker is opening on top of the keyboard? It should use the exactly same space and design as keyboard is using, also showing the text of the user on the top; (Look at this, maybe this is the way to go: a new input method for Emojis: https://developer.android.com/guide/topics/text/creating-input-method.html)
- [x] When you get to the end of the list, there are 0px between the bottom of the device and the bottom of the emojis. Let's add at least 16px of space;

**Review by rafaelks — APPROVED** [review]
Feature is looking good to me, but I didn't review all the code changes! 👍

@leonardoaramaki I think your PR have some conflicts to resolve before merging.

**Review by antgel — COMMENTED** [review]
Always an option to rebase a feature branch rather than add merge commits...

**Comment by leonardoaramaki** [comment]
@antgel Indeed, thanks for pointing out

**Pull request merged**
