### PR TITLE
[NEW] Support to login using Custom OAuth

### PR DESCRIPTION
**Pull request by philipbrito**
This PR adds the support of custom OAuth (using the same button style from the server).

Closes https://github.com/RocketChat/Rocket.Chat.Android/issues/322

### CODE REVIEW

**Review by rafaelks — APPROVED** [review]
Working great for me @filipedelimabrito! 👏

**Comment by cmassi** [comment]
Using rocket.chat server 0.63.1, with keycloak login, the https://server/api/v1/settings.oauth , does not answer with custom:true , so the keycloak button is not enabled in android app. I've been able to login only using 0.64.2 as rocket.chat server. If confirmed, the REQUIRED_SERVER_VERSION should be raised to 0.64.x

**Comment by rafaelks** [comment]
@cmassi Is `keycloak` a custom OAuth? What's the response from the API?

**Comment by cmassi** [comment]
@rafaelks According to documentation, https://www.keycloak.org/about.html, Keycloak is based on standard protocols and provides support for OpenID Connect, OAuth 2.0, and SAML. 

Before upgrade 

https://wetalk.sorint.it/api/v1/info
{"info":{"version":"0.63.1"},"success":true}

https://wetalk.sorint.it/api/v1/settings.oauth
{"services":[{"id":"J7W9aZB3Rfj5x9G3X","name":"keycloak","appId":"rocketchat","buttonLabelText":"Login with Sorint!","buttonColor":"#13679A","buttonLabelColor":"#FFFFFF"}],"success":true}

After upgrade (I changed only buttonLabelText and buttonColor, in server settings):

https://wetalk.sorint.it/api/v1/info
{"info":{"version":"0.64.2"},"success":true}

https://wetalk.sorint.it/api/v1/settings.oauth
{"services":[{"_id":"J7W9aZB3Rfj5x9G3X","service":"keycloak","clientId":"rocketchat","custom":true,"serverURL":"https://login.sorint.it/auth","tokenPath":"/realms/sorint/protocol/openid-connect/token","identityPath":"/realms/sorint/protocol/openid-connect/userinfo","authorizePath":"/realms/sorint/protocol/openid-connect/auth","scope":"openid","buttonLabelText":"Login@Sorint","buttonLabelColor":"#FFFFFF","loginStyle":"redirect","buttonColor":"#FF9EC938","tokenSentVia":"header","identityTokenSentVia":"default","usernameField":"preferred_username","mergeUsers":true}],"success":true}

----

Furthermore, to improve usabiity, I have had to change code in LoginPresenter.kt (https://github.com/RocketChat/Rocket.Chat.Android/blob/master/app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt) , because with default code I get the name of the service in the button label instead of the the value defined on server side as buttonLabelText

In view.addCustomOauthServiceButton(...,serviceName,getCustomOauthServiceNameColor(service),...) instead of serviceName for button label text, I've used my getCustomOauthServiceNameText(service) , e.g:

  private fun getCustomOauthServiceNameText(service: Map<String, Any>): String { 
       return service["buttonLabelText"].toString()
    }

**Comment by rafaelks** [comment]
@cmassi Yes, we now have a way to know if the OAuth is custom or not... I'm not following what issue you're having.

**Comment by cmassi** [comment]
When using a server 0.63.1 , where only OAuth custom login is enabled, the Login frame of Android app is empty. This is the RECOMMENDED_SERVER_VERSION in app/build.gradle. So I'm asking to raise REQUIRED_SERVER_VERSION and/or RECOMMENDED_SERVER_VERSION to an appropriate version, like 0.64.2

**Comment by rafaelks** [comment]
@cmassi Got it! Thank you for pointing that for us! 👍

**Comment by philipbrito** [comment]
@cmassi Here is the PR that changes the recommended server version: https://github.com/RocketChat/Rocket.Chat.Android/pull/1340

Thanks for bringing us your comments.

**Pull request merged**
