### PR TITLE
[IMPROVEMENT] Change date format

### LINKED ISSUE #1520: [IMPROVEMENT] Change date format
## Description
It's better if we have date format from "24/07/2018" to "Jul 24, 2018". This format will match with our web app also and it's readability is better.

### PR DESCRIPTION
**Pull request by divyanshub024**
@RocketChat/android

Closes #1520 
screenshot_1532500366

### CODE REVIEW

**Comment by rafaelks** [comment]
@divyanshub024 Great change! Does it uses the default region format from the device? I think that's the best approach.

**Comment by rafaelks** [comment]
@divyanshub024 I think if you change from .SHORT to .MEDIUM it should look like that.

**Comment by divyanshub024** [comment]
@rafaelks Yes you are right. I have made the changes.

**Comment by rafaelks** [comment]
LGTM!

**Review by philipbrito — APPROVED** [review]

**Pull request merged**
