### PR TITLE
[I18N] update (IT) and (hi) strings.xml 

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
useful for #1909 and #1918 

Some more updates to strings.xml and #1918 would be good to go for🚀

### CODE REVIEW

**Comment by rafaelks** [comment]
@GOVINDDIXIT Did you translate it by your own or used some service to do it?

**Comment by GOVINDDIXIT** [comment]
I have translated (hi)strings.xml on my own and used google translator for (it)

**Comment by rafaelks** [comment]
@GOVINDDIXIT Thank you! 👍

**Review by rafaelks — APPROVED** [review]

**Comment by rafaelks** [comment]
@GOVINDDIXIT Can you remove the Italian translations from Google Translate from the PR? There's another PR opened from a native speaker. Thank you! 👍

**Comment by GOVINDDIXIT** [comment]
@rafaelks  Sure. I also think that native speaker will be a far better option than google translate 😃

**Pull request merged**
