### PR TITLE
[NEW] Added unread on top filter

### LINKED ISSUE #1660: [FEATURE] Add "Unread on top" as in Rocket.Chat.ReactNative
Please add `All Unreads` / `Unread on top` feature.

I tried https://github.com/RocketChat/Rocket.Chat.ReactNative and there is `Unread on top`:
screenshot_2018-09-06-15-04-01-461_chat rocket reactnative

But in "default" android client https://github.com/RocketChat/Rocket.Chat.Android is not possible to have unread on top:
screenshot_2018-09-06-15-04-10-485_chat rocket android

### PR DESCRIPTION
**Pull request by dabbler011**
@RocketChat/android

Closes #1660 

ezgif com-resize 1

### CODE REVIEW

**Comment by zdumitru** [comment]
@dabbler011 Can you please give me access? I will rebase the pull request.

**Comment by tuxmartin** [comment]
@dabbler011 do you have any updates to this feature? It would be very useful for me.

**Comment by dabbler011** [comment]
@tuxmartin PR is completed from my side, waiting for it to be reviewed.

**Comment by tuxmartin** [comment]
@rafaelks do you have a time estimate when it could be done?
Thank you!

**Comment by rafaelks** [comment]
@tuxmartin We're doing our best to catch up with all opened PRs... this one will be reviewed soon. 👍

**Review by philipbrito — COMMENTED** [review]
@dabbler011 Feature is looking good but it would be great to have a section for the unread messages like we have currently for favorite, channels and private groups. Web is doing that too.

Could you make that?
Thank you.

Note: Make sure to follow our coding style. I fixed some formatting issues here.

**Comment by dabbler011** [comment]
@filipedelimabrito as per the current PR if both unread on top and group by type are selected, division on the basis of type takes place first, then unread gets on top in each category.

However, I think in web first unread goes to top then after that type division takes place. 

Should I try to make it as per web or just add unread divisions in each category separately?

**Comment by philipbrito** [comment]
@dabbler011 Acting like the web (by having a single unread division/category for the unread messages)  is fine! Could you do it?

**Comment by zdumitru** [comment]
@dabbler011 Can you, please, give me write access? I will try to resolve merge conflicts.

**Pull request closed without merging**
