### PR TITLE
[FIX] refactor: Update build-sdk.sh

### LINKED ISSUE #773: [BUG] build-sdk.sh not working
Your Rocket.Chat.Android version: 2.0.0
Mobile device model and OS version: Moto G4 Plus - Android 7.0

`build-sdk.sh` script is not working properly and gives following log.

**reproduce issue**
- cd app
- ./build-sdk.sh

**log**
```
CURRENT DIR: /home/shell/Git Projects/Rocket.Chat.Android/app
SDK DIR: /home
Projects/Rocket.Chat.Kotlin.SDK
./build-sdk.sh: line 35: cd: too many arguments
./build-sdk.sh: line 73: cd: too many arguments
./build-sdk.sh: line 30: cd: too many arguments
CURRENT SHA: 0.1-SNAPSHOT
./build-sdk.sh: line 17: cd: too many arguments
./build-sdk.sh: line 24: cd: too many arguments
is dirty
./build-sdk.sh: line 90: cd: too many arguments
./build-sdk.sh: line 91: cd: too many arguments
rm: cannot remove '/home/shell/Git': No such file or directory
rm: cannot remove 'Projects/Rocket.Chat.Android/app/libs/common*': No such file or directory
rm: cannot remove '/home/shell/Git': No such file or directory
rm: cannot remove 'Projects/Rocket.Chat.Android/app/libs/core*': No such file or directory
cp: target 'Projects/Rocket.Chat.Android/app/libs/common-0.1-SNAPSHOT.jar' is not a directory
cp: target 'Projects/Rocket.Chat.Android/app/libs/core-0.1-SNAPSHOT.jar' is not a directory
./build-sdk.sh: line 99: $SDK_DIR/.last_commit_hash: ambiguous redirect
```

### PR DESCRIPTION
**Pull request by Shailesh351**
@RocketChat/android

Closes #773 

**Changes**
- Updated build-sdk.sh file

**log after changes**
```
CURRENT DIR: /home/shell/Git Projects/Rocket.Chat.Android/app
SDK DIR: /home/shell/Git Projects/Rocket.Chat.Kotlin.SDK
CURRENT SHA: 99b4ce6
 1 file changed, 1 insertion(+), 1 deletion(-)
is dirty

BUILD SUCCESSFUL in 0s
5 actionable tasks: 5 up-to-date

BUILD SUCCESSFUL in 0s
10 actionable tasks: 10 up-to-date
'/home/shell/Git Projects/Rocket.Chat.Kotlin.SDK/common/build/libs/common-0.1-SNAPSHOT.jar' -> '/home/shell/Git Projects/Rocket.Chat.Android/app/libs/common-99b4ce6.jar'
'/home/shell/Git Projects/Rocket.Chat.Kotlin.SDK/core/build/libs/core-0.1-SNAPSHOT.jar' -> '/home/shell/Git Projects/Rocket.Chat.Android/app/libs/core-99b4ce6.jar'
```

### CODE REVIEW

**Comment by Shailesh351** [comment]
@leonardoaramaki @luciofm Please review :smile:

**Comment by luciofm** [comment]
@Shailesh351 will review it later today...

**Comment by luciofm** [comment]
@Shailesh351 looks good to me... Could you confirm if it would work on Windows also?

**Comment by Shailesh351** [comment]
@luciofm Yes Script works fine in WIndows also, but the command for running script in build.gradle(app) file is different for linux and windows.

**Comment by Shailesh351** [comment]
@luciofm Now works perfect on both linux and windows

**Pull request merged**
