### PR TITLE
fixed error : Update your app theme to inherit from Theme.MaterialCom…

### PR DESCRIPTION
**Pull request by leeyc09**
…ponents.

If you using MateralComponents you must Update your app theme to inherit from Theme.MaterialComponents

@RocketChat/android

### CODE REVIEW

**Comment by philipbrito** [comment]
@luciofm Could you confirm if we'll use `Theme.MaterialSomething` instead of using `Theme.AppCompat`. I remember a discussion to prefer supporting AppCompat instead of MaterialSomething in the past.

**Comment by luciofm** [comment]
MaterialComponents is the way to go, but we need to test a little this build first... https://material.io/develop/android/docs/getting-started/

**Comment by philipbrito** [comment]
Related: https://github.com/RocketChat/Rocket.Chat.Android/issues/1634

**Comment by philipbrito** [comment]
As discussed in this [issue](https://github.com/RocketChat/Rocket.Chat.Android/issues/1634) there are some questions happening with the Material Components so I am closing this PR while the MC gets matured and we really care about its behaviour on the entire Rocket.Chat Android app.

Thanks for your PR @leeyc09!

**Pull request closed without merging**
