### PR TITLE
[PROJECT] gradle(globally declare library) changes

### PR DESCRIPTION
**Pull request by mala2017**
i declared all the common dependencies in project level dependencies.gradle and used in module .

### CODE REVIEW

**Review by leonardoaramaki — CHANGES_REQUESTED** [review]
@mala9974025544 Thanks for your PR! :)
It's much cleaner. I've been wanting to do what you did for a long time... Thanks.
I would like to ask you though to remove some empty lines that are taking lots of space on the gradle files (big blocks of empty lines).
Also I'm missing this dependency:
debugCompile "com.tspoon.traceur:traceur:1.0.1"
It's originally been declared on the main app project. Can you add this?

**Comment by mala2017** [comment]
Thanks for reply
Sorry for my let reply because of weekend holiday .i am pushing with new
changes ,please check now
waiting  for your reply..
Thank you

Mala Ruparel

**Review by mala2017 — COMMENTED** [review]
i did the changes as your comment

**Comment by leonardoaramaki** [comment]
Thanks @mala9974025544! Gonna check it soon :)

**Review by leonardoaramaki — APPROVED** [review]
Looks fine now @mala9974025544!
Thanks for your contribution :+1:

**Pull request merged**
