### PR TITLE
[IMPROVEMENT] Change from long-press to "tap" to show the actions of the message

### LINKED ISSUE #1221: [IMPROVEMENT] Change from long-press to "tap" to show the actions of the message

### PR DESCRIPTION
**Pull request by divyanshub024**
@RocketChat/android

Closes #1221

### CODE REVIEW

**Comment by rafaelks** [comment]
@divyanshub024 Thanks for the PR! We're still planning on how to do it, so I'll leave your PR opened for now.

**Comment by divyanshub024** [comment]
@rafaelks I have just change onLongClick to onClick. Let me know for any other changes.

**Comment by rafaelks** [comment]
@divyanshub024 Can you fix the conflicts please?

**Review by philipbrito — APPROVED** [review]
Thanks for this PR @divyanshub024!

**Pull request merged**
