### PR TITLE
[NEW] Added Chat Room Information

### LINKED ISSUE #835: [NEW] Display Chat Room Information
**Feature**
Add a room option which displays in a _small pop-up window_ the information about a public chat room (such as its topic, last announcement, creator, etc.)

**Willing to work on this**
Yes

### PR DESCRIPTION
**Pull request by samrmur**
@RocketChat/android

Closes #835

**PR Info**
Adds the capability of viewing a chat room's information. This works for both subscribed and unsubscribed rooms.

Information that can be viewed:
- Channel Name
- Topic
- Description
- Announcement

Note: Could not find all icons that were shown in mock. Can implement those if available.

**Screenshot**

### CODE REVIEW

**Review by leonardoaramaki — CHANGES_REQUESTED** [review]
The description of the channel is showing the channel name. Tested it on group (private channel). Can you check this?

**Comment by samrmur** [comment]
@leonardoaramaki Added changes but only commit after Kotlin SDK's [#111](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/111).

**Comment by samrmur** [comment]
@rafaelks @leonardoaramaki This is ready to be re-reviewed. Sorry it took so long. Last month of school has been tough so I wasn't able to put in a lot of time all at once to get this done quickly.

**Comment by samrmur** [comment]
Just to update, will try and fix conflicts for this PR in during the next two weeks

**Comment by rafaelks** [comment]
@thiagosanchz Let's discuss about the details of this screen please.

**Comment by thiagosanchz** [comment]
Guys, we can discuss that, but one important thing is using the same features, labels, and button as a desktop/web app to keep product decision aligned. But we can do a better job in the layout.

**Comment by rafaelks** [comment]
@samrmur Can you please fix the conflicts and the code? Because it's not compiling (and there are some conflicts inside the code that was commited).

**Comment by rafaelks** [comment]
Closing the PR for now, let me know if you still want to have this one merged @samrmur, than we can reopen it.

**Comment by samrmur** [comment]
@rafaelks This PR is finally ready to be merged

**Pull request closed without merging**
