### PR TITLE
render Markdown link

### LINKED ISSUE #83: [v1.0-beta] render link, image-link
render

`[link](http://demo.rocket.chat)`

`image`

ref: RocketChat: packages/rocketchat-markdown/markdowncode.coffee

### PR DESCRIPTION
**Pull request by YusukeIwaki**
@RocketChat/android

Closes #83

* hide `image ` because it is rendered as attachment.
* render links with `[link](http://example.com/)` and `<http://example.com/|link>` formatted only not in single-line code.

slice

### CODE REVIEW

**Comment by YusukeIwaki** [comment]
`<http://example.com/|link>` causes crash. I will fix it.

**Comment by geekgonecrazy** [comment]
Yeah I don't think the web client supports that.  All those links we get from slack in imports we transform them

**Comment by YusukeIwaki** [comment]
slice

fixed.

**Comment by laggedHero** [comment]
@YusukeIwaki What about caching those compiled patterns? =

We could make each pattern a static field.

What do you think?

**Comment by YusukeIwaki** [comment]
@laggedHero Thank you for good advice.

It should be better to define Pattern as static. I will fix it.

**Review by laggedHero — APPROVED** [review]

**Pull request merged**
