### PR TITLE
[REFACTOR] Modularizing rocket.chat.android

### PR DESCRIPTION
**Pull request by alexfdz**
@RocketChat/android

This is a PR implementing the feature request [Multi-module architecture for Rocket.Chat.Android](https://forums.rocket.chat/t/multi-module-architecture-for-rocket-chat-android).

This refactor follows the approach proposed by Marvin Ramin's talk at the droidcon London 2017 ["Modularizing Android Applications"](https://skillsmatter.com/skillscasts/10525-modularizing-android-applications#video).

To minimise changes we have not renamed the current `:app` module to `:base` as suggested by Marvin. Is up to the team if they want to do some renaming clean-up.

This refactor contains:

* Refactor the current android application module `:app` as an android library module with views, configuration and logic
* New android application module `:application` with the AndroidManifest application definitions and instrumentation tests

Now we are in a much better place for the following:
* Rocket.Chat.Android developers can start an "as needed" refactor to extract modules from `:app` and profit from the benefits of a multi-module architecture (check first link).
* Vendor-specific developers can add more `:my-own-app` android application modules in their own forked repos and customize look and feel, extend activities and add their own magic. Some of this magic could easily be contained in another android library module and offered to the main Rocket.Chat repo.

### CODE REVIEW

**Comment by LluisFelip** [comment]
Hi guys!

I was checking the failing checks of circleci and tried to figure out what commands are being executed by it, are they these?:

- ./gradlew assembleFossRelease --info --console=plain --stacktrace

- ./gradlew assemblePlayRelease --info --console=plain --stacktrace

- ./gradlew lint

I executed them in local over @alexfdz 's PR and they are building successfully.

Could you give us any hint so we can figure out how we can fix them so it passes all the ci tests? :)

Thanks in advance!

**Comment by luciofm** [comment]
@alexfdz can you solve the small conflict, so we can move ahead with this refactor?

**Comment by alexfdz** [comment]
@luciofm the CI failure does not seem related to the refactor.

```
/home/circleci/project/app/src/play/java/chat/rocket/android/analytics/GoogleAnalyticsForFirebase.kt:13: Error: Missing permissions required by FirebaseAnalytics.getInstance: android.permission.ACCESS_NETWORK_STATE and android.permission.WAKE_LOCK [MissingPermission]
      private val firebaseAnalytics = FirebaseAnalytics.getInstance(context)
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Applies to variants: playDebug, playRelease
```

**Comment by luciofm** [comment]
@alexfdz yes, gonna checkout the branch and check it out

**Comment by rafaelks** [comment]
@alexfdz We discussed internally about modularising this part of the app and we came to the conclusion that right now modularising it would generate more complexity that we don't want to have to deal right now. Thank you very much for your PR and I'm sure we will want to modularize the app in some way in the future. Again, thanks a lot for your efforts! 👍

**Pull request closed without merging**
