### PR TITLE
[NEW] Show version name/code in about screen

### LINKED ISSUE #920: [IMPROVEMENT] Show version name/number under settings

### PR DESCRIPTION
**Pull request by divyanshub024**
@RocketChat/android

Closes #920 #962 

about

### CODE REVIEW

**Comment by aniketsingh03** [comment]
@divyanshub024 It would be a better choice to show the version number at the bottom of the activity/fragment. What do you think @filipedelimabrito @rafaelks ?

**Comment by divyanshub024** [comment]
@aniketsingh03 I agree with you. Even in most of the apps, the version name is at the bottom because they have lots of things in their settings. If I keep the version name in the bottom there will be lots of space in between which I think is not right.

**Comment by Shailesh351** [comment]
Why don't just add about section and show all the info of app - Version name, number, with logo?

**Comment by divyanshub024** [comment]
@Shailesh351 yeah you are right. According to material design guidelines "Settings should not: Contain information about the app, such as a version or licensing information (Move these to a Help screen)"
https://material.io/guidelines/patterns/settings.html#settings-usage

**Comment by philipbrito** [comment]
Love when someone points to a truly reference (in our case, the material guidelines - in terms of UI/UX - is what we should follow for now).

**Comment by divyanshub024** [comment]
@filipedelimabrito I think we should make an About screen as @Shailesh351 proposed. Something like this.
about

**Comment by leonardoaramaki** [comment]
@divyanshub024 The about screen on screenshot looks nice. Is it already implemented on this PR?

**Comment by leonardoaramaki** [comment]
@rafaelks I'm adding this to the 2.0.0 milestone since I think it would be useful to have this so that non dev users can easily spot the version of the app when reporting issues.

**Comment by divyanshub024** [comment]
@leonardoaramaki no I haven't implemented yet. I was waiting for someone's approval. I'll start working on this.

**Comment by divyanshub024** [comment]
@leonardoaramaki the about screen implementation is done. Please review it.

**Comment by rafaelks** [comment]
@leonardoaramaki Please review it and merge if it's OK.

**Comment by rafaelks** [comment]
I tried many times already running the CI on this PR but it always fails... can you confirm if this is still working @divyanshub024 please?

**Comment by divyanshub024** [comment]
Closing this PR as it is having some issues. Clone: #989

**Pull request closed without merging**
