### PR TITLE
[NEW][IMPROVEMENT] feat: Add Grouping by Favourite Rooms

### LINKED ISSUE #988: [NEW] Support 'favorites' for channels and users in chat list
Your Rocket.Chat.Android version: v2.0.0-alpha1

The standard 'chats' view is a list of all users and channels that the current user has participated in.  There is currently no way to pin a particular user or channel to the top of this list like there is in the web-UI.  The web-UI uses the 'favorites' notion to create this pinned list, and it would be natural to extend this to the Android app.

This is related to, but different from #880 which addresses the order in which the chats are sorted (independent of 'favorites').

### PR DESCRIPTION
**Pull request by Shailesh351**
@RocketChat/android

Closes #988

**Changes**
- Added grouping by favoutrites

### CODE REVIEW

**Comment by Shailesh351** [comment]
@rafaelks @leonardoaramaki @luciofm @filipedelimabrito Have a look.
Ensure https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/116 is added  while testing

**Comment by Shailesh351** [comment]
@rafaelks Resolved conflicts. PR ready for review.

**Comment by rafaelks** [comment]
@Shailesh351 Looks like your PR is missing some translations: https://circleci.com/gh/RocketChat/Rocket.Chat.Android/2746, can you take a look?

**Comment by rafaelks** [comment]
@Shailesh351 App is crashing for me on start... Android 6.x

**Comment by Shailesh351** [comment]
@rafaelks I tested it again. Working fine for me. Can you please check it again? Ensure you pulled latest changes. Thanks!!

**Comment by rafaelks** [comment]
@Shailesh351 Still crashes all the time for me. Stacktrace:

```
ChatRoomsPresenter.kt line 229
chat.rocket.android.chatrooms.presentation.ChatRoomsPresenter$compareByLastMes

Fatal Exception: kotlin.KotlinNullPointerException
       at chat.rocket.android.chatrooms.presentation.ChatRoomsPresenter$compareByLastMessage$1.compare(ChatRoomsPresenter.kt:229)
       at chat.rocket.android.chatrooms.presentation.ChatRoomsPresenter$compareByLastMessage$1.compare(ChatRoomsPresenter.kt:34)
       at java.util.TimSort.binarySort(TimSort.java:261)
       at java.util.TimSort.sort(TimSort.java:204)
       at java.util.TimSort.sort(TimSort.java:169)
       at java.util.Arrays.sort(Arrays.java:2010)
       at kotlin.collections.ArraysKt___ArraysKt.sortWith(_Arrays.kt:6685)
       at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:882)
       at chat.rocket.android.chatrooms.presentation.ChatRoomsPresenter.getSortedAndGroupedByTypeRooms(ChatRoomsPresenter.kt:215)
       at chat.rocket.android.chatrooms.presentation.ChatRoomsPresenter.sortRooms(ChatRoomsPresenter.kt:199)
       at chat.rocket.android.chatrooms.presentation.ChatRoomsPresenter.loadRooms(ChatRoomsPresenter.kt:167)
       at chat.rocket.android.chatrooms.presentation.ChatRoomsPresenter$loadRooms$1.doResume(ChatRoomsPresenter.kt)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
       at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
       at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5763)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by Shailesh351** [comment]
@rafaelks I have rebased PR on latest develope and fixed crash. PR ready for re-review.

**Comment by rafaelks** [comment]
@Shailesh351 Thanks for the update. The grouping by favorites now is working fine, but the sorting by activity is totally messed up. It's not sorted by activity correctly anymore. Can you take a look please?

**Comment by Shailesh351** [comment]
@rafaelks Thanks for testing. The whole time i was using lastMessage.timestamp for sort by activity which in some case can be null according to server setting i guess.
And also may be because of it it is giving this issue https://github.com/RocketChat/Rocket.Chat.Android/issues/1105 

Now i have used updatedAt field of Room object for it and it works perfect.

**Pull request closed without merging**
