### PR TITLE
Fixes possible race condition

### LINKED ISSUE #276: Possible race condition?
#260 may have introduced a race condition if KeyboardHelper.hideSoftKeyboard runs in another thread (not in the UI thread).

I'm geting started with Android development and would appreciate feedback if this isn't the case. Thanks!

### PR DESCRIPTION
**Pull request by rcoelho**
@RocketChat/android

Closes #276

### CODE REVIEW

**Comment by laggedHero** [comment]
Hello @rcoelho, and welcome!

First the boring part: did you signed that agreement?

Now, the fun part: I like you PR. I don't think we would have a race condition there, but it makes it better anyway.

As soon as we get the agreement stuff done, let's merge it.

**Comment by rcoelho** [comment]
I'm sorry, I'm not sure I can sign. That's a small change, though, feel free to replicate it.
Thanks for your feedback!

**Comment by geekgonecrazy** [comment]
@rcoelho its as easy as clicking here: [CLA assistant check](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=277)

**Comment by rcoelho** [comment]
@geekgonecrazy oh, yeah, I did and I read the CLA. Sorry for not being clear on what's the problem. I'm not clear I can sign the CLA due to the patent stuff, I'm sorry.

**Comment by rafaelks** [comment]
@rcoelho Will you be able to sign our CLA? We require it to merge your PR.

**Comment by rcoelho** [comment]
Hi @rafaelks, I'm sorry I won't be able to sign it due to the reasons I commented above.
But that's a small change on the code anyway, feel free to replicate it.

**Comment by rafaelks** [comment]
@rcoelho Sounds good! Can you take a look @matheusjardimb?

**Comment by matheusjardimb** [comment]
@rafaelks sure! Thanks, @rcoelho!

**Pull request closed without merging**
