### PR TITLE
[NEW] Add day marker in chatroom

### LINKED ISSUE #825: [NEW] Add day marker for messages in chatroom
Implement a day marker for messages in the chatroom so that it will display Today, Yesterday or date according to the requirement (like the one implemented in version 1.1.0).

I would like to work on this feature.

### PR DESCRIPTION
**Pull request by joeljacobdev**
Added Day Marker for messages in chatroom

Closes #825 

screenshot_20180313-153932

### CODE REVIEW

**Comment by rafaelks** [comment]
@pcforgeek Thank you very much for the PR! Feature is working really nice! I had one crash while scrolling thought the messages, not sure if it's related to this change or not. 👍

**Comment by joeljacobdev** [comment]
@rafaelks Happy to help. I didn't face any such issues on my system, but I do hope that you resolve this issue. Let me know if you need any further help regarding this.

**Comment by leonardoaramaki** [comment]
@pcforgeek Could you please solve the conflicts?

**Comment by joeljacobdev** [comment]
@leonardoaramaki Solved the conflicts.

**Comment by luciofm** [comment]
There are a lot of indentation problems on this PR, like `if(data.showDayMarker){`

You should take a look on the [Kotlin Coding Convetions](https://kotlinlang.org/docs/reference/coding-conventions.html) to reformat the code.

**Comment by joeljacobdev** [comment]
@luciofm Changes made.

**Comment by rafaelks** [comment]
@pcforgeek I'm sorry, but there are some new conflicts on your PR... can you take a look and @luciofm can you review as soon as he fixes it, please?

**Comment by joeljacobdev** [comment]
@rafaelks @luciofm Fixed the conflicts.

**Review by rafaelks — CHANGES_REQUESTED** [review]
@pcforgeek Thanks for the PR, but looks like it changed the alignment of username & message text. Can you take a look?

screenshot_20180331-162118

**Comment by rafaelks** [comment]
@pcforgeek I also got an error "Index 0 of 0..." when going to the beginning of a list.

**Comment by joeljacobdev** [comment]
@rafaelks Changes made. Thanks for pointing about Index 0 of 0 error.

**Comment by reetp** [comment]
Is there any movement on this or work via another bug ?

**Comment by Amirko28** [comment]
I've tried implementing this branch into a fork of RocketChat and found a bug.
When i send a message on a different day, it doesn't show the day marker. Only after I re-enter the chatroom it shows the day marker. Is it intentional?

**Comment by rafaelks** [comment]
@leonardoaramaki is going to fix the conflicts of this PR, make some code adjustments and merge it for the 2.5.0 release! 🎉

**Pull request merged**
