### PR TITLE
[IMPROVEMENT] Adds animation when expanding/collapsing the login options

### PR DESCRIPTION
**Pull request by hfeky**
@RocketChat/android

#### Changes:

Added animation when expanding/collapsing login options using `ValueAnimator`.

#### Screenshots or GIF for the change:

Login Animation

### CODE REVIEW

**Comment by philipbrito** [comment]
Looking really nice @HusseinElFeky! ❤️

**Review by philipbrito — CHANGES_REQUESTED** [review]
There are some wrong code formatting here. Please follow our coding style.

**Comment by philipbrito** [comment]
@divyanshub024 is the dev who really likes playing with animations here. Feel free to review it too @divyanshub024 .

**Comment by hfeky** [comment]
Thank you @filipedelimabrito! Ah yes, my mistake regarding code formatting. I just usually use Android Studio Format Code shortcut every while and then, and that must have been the reason. I have just adjusted the continuation indent to be 4 right now through Android Studio's settings. Thanks for the heads up!

**Review by philipbrito — CHANGES_REQUESTED** [review]
@HusseinElFeky Animations is really looking good, but it is showing wrong (disable) login options for some servers. Could you fix it, please?

**Comment by hfeky** [comment]
@filipedelimabrito I have fixed incorrect login options showing up for some servers. Please let me know if there is any other issue.

**Review by philipbrito — APPROVED** [review]
It is working like a charm now. Thanks @HusseinElFeky!

**Pull request merged**
