### PR TITLE
Improvements on getting the user avatar.

### PR DESCRIPTION
**Pull request by philipbrito**
@RocketChat/android

This PR improves the way to get users avatar (sometimes the `absoluteUrl` may be broken).

### CODE REVIEW

**Comment by rafaelks** [comment]
Loved the changes from Java to Kotlin 👏 👍

**Comment by rafaelks** [comment]
LGTM! Can someone review it too? @leonardoaramaki, @luciofm

**Comment by luciofm** [comment]
@filipedelimabrito can you rebase with develop?

**Review by luciofm — APPROVED** [review]
:+1:

**Comment by rafaelks** [comment]
@luciofm I did rebase it, let's wait for tests and merge it.

**Pull request merged**
