### PR TITLE
[I18N] Update RU strings.xml

### PR DESCRIPTION
**Pull request by Pitstopper**
All recent changes have been translated.

### CODE REVIEW

**Comment by philipbrito** [comment]
Could you see why is it failing, @Pitstopper ?

**Comment by Pitstopper** [comment]
@filipedelimabrito For my part, there are no errors in the translation and the syntax of the translation.

**Comment by Pitstopper** [comment]
Tomorrow I can check line by line.

**Comment by GOVINDDIXIT** [comment]
@Pitstopper there is no problem in translation part. The problem is here inside download dependencies

> FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.google.gms:google-services:4.1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/gms/google-services/4.1.0/google-services-4.1.0.pom
       - https://dl.google.com/dl/android/maven2/com/google/gms/google-services/4.1.0/google-services-4.1.0.jar
       - https://jcenter.bintray.com/com/google/gms/google-services/4.1.0/google-services-4.1.0.pom
       - https://jcenter.bintray.com/com/google/gms/google-services/4.1.0/google-services-4.1.0.jar
       - https://maven.fabric.io/public/com/google/gms/google-services/4.1.0/google-services-4.1.0.pom
       - https://maven.fabric.io/public/com/google/gms/google-services/4.1.0/google-services-4.1.0.jar
       - https://repo.maven.apache.org/maven2/com/google/gms/google-services/4.1.0/google-services-4.1.0.pom
       - https://repo.maven.apache.org/maven2/com/google/gms/google-services/4.1.0/google-services-4.1.0.jar

I will suggest you to update your repo and  fix above error

**Review by GOVINDDIXIT — CHANGES_REQUESTED** [review]
@Pitstopper I don't think that translation part has caused this. The problem is here inside download dependencies

FAILURE: Build failed with an exception.

What went wrong:
A problem occurred configuring root project 'project'.
Could not resolve all artifacts for configuration ':classpath'.
Could not find com.google.gms:google-services:4.1.0.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/com/google/gms/google-services/4.1.0/google-services-4.1.0.pom
- https://dl.google.com/dl/android/maven2/com/google/gms/google-services/4.1.0/google-services-4.1.0.jar
- https://jcenter.bintray.com/com/google/gms/google-services/4.1.0/google-services-4.1.0.pom
- https://jcenter.bintray.com/com/google/gms/google-services/4.1.0/google-services-4.1.0.jar
- https://maven.fabric.io/public/com/google/gms/google-services/4.1.0/google-services-4.1.0.pom
- https://maven.fabric.io/public/com/google/gms/google-services/4.1.0/google-services-4.1.0.jar
- https://repo.maven.apache.org/maven2/com/google/gms/google-services/4.1.0/google-services-4.1.0.pom
- https://repo.maven.apache.org/maven2/com/google/gms/google-services/4.1.0/google-services-4.1.0.jar

I will suggest you to update your repo and fix above error
For more inside have a look on CircleCI reports

**Comment by Pitstopper** [comment]
@GOVINDDIXIT got it, thanks! Tomorrow i'll do it

**Pull request closed without merging**
