### PR TITLE
[NEW] Bottom sheet for pinned messages

### LINKED ISSUE #852: [New] [UX] There should be an option to unpin the pinned messages from "Pinned Message" activity
**Rocket.Chat.Android version:**
versionCode 1009
versionName "2.0.0-dev7"

# Description
Option to unpin the messages pinned by you is not there in pinned message activity.

**Willing to work on it?** YES

### PR DESCRIPTION
**Pull request by divyanshub024**
@RocketChat/android

Closes #852 

This PR add option to unpin message from PinnedMessageActivity

unpin1

### CODE REVIEW

**Comment by rafaelks** [comment]
@divyanshub024 Thanks for the PR! The PR contains some conflicts... can you also only allow the user unpin the message from this screen and nothing else? Thank you!

**Comment by divyanshub024** [comment]
@rafaelks so there will be only "unpin message" option in bottom sheet and other option will be hidden, Right?

**Comment by rafaelks** [comment]
@divyanshub024 Positive! 👍

**Comment by divyanshub024** [comment]
@rafaelks requested changes has been made. Please review it. Thanks!

**Comment by rafaelks** [comment]
@divyanshub024 Could you please fix the conflicts?

**Comment by divyanshub024** [comment]
@rafaelks done!

**Comment by divyanshub024** [comment]
@rafaelks this PR is ready for review.

**Pull request closed without merging**
