### PR TITLE
[FIX] About Screen in landscape view

### LINKED ISSUE #2062: [IMPROVEMENT] Fix About Screen in landscape view.
## Description

The about page UI in overflowed in landscape view. It's better to put it in the scroll view.

### PR DESCRIPTION
**Pull request by arthurbdiniz**
Signed-off-by: Arthur Diniz <arthurbdiniz@gmail.com>

@RocketChat/android

Closes #2062 

#### Screenshots or GIF for the change:
screenshot_20190228-173746_rocketchat
screenshot_20190228-173808_rocketchat

### CODE REVIEW

**Review by philipbrito — CHANGES_REQUESTED** [review]
No need to keep three layouts here. 
Just declare `<ScrollView ...` as the root layout and keep using `<ConstraintLayout..` bellow.

**Comment by arthurbdiniz** [comment]
> No need to keep three layouts here.
> Just declare `<ScrollView ...` as the root layout and keep using `<ConstraintLayout..` bellow.

Ok, fixing this requested changes

**Comment by arthurbdiniz** [comment]
@filipedelimabrito, the ```ScrollView``` is now the root layout.  😄

**Review by philipbrito — APPROVED** [review]
Thank you very much for doing this @arthurbdiniz!

**Pull request merged**
