### PR TITLE
[CHORE] Realm Stetho - Increase table view data limit

### PR DESCRIPTION
**Pull request by JigneshWorld**
@RocketChat/android As there was limited view of table while debugging realm database
https://github.com/uPhyca/stetho-realm/issues/2

### CODE REVIEW

**Comment by luciofm** [comment]
Thanks for the PR @JigneshPatel23, will take a look on how it perform with such a big limit...

**Comment by JigneshWorld** [comment]
Sure @luciofm. FYI I have checked with approx 1000 data in one of the table till then it works fine and it will be applicable while debugging only.

**Comment by rafaelks** [comment]
@JigneshPatel23 Thanks for your PR! 👍

**Comment by JigneshWorld** [comment]
@rafaelks Thanks.

**Pull request merged**
