### PR TITLE
[FIX] roomid or username required bug

### LINKED ISSUE #1912: [BUG] `Body param "roomid" or "username" is required [error-room-param-not-provided]`
Your Rocket.Chat.Android version: 3.2.0 Build 2052 - a830e92 - play
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9.6 (9.6.2.0) , Global Stable
Your Rocket.Chat Server version: 0.72.1

Attempting to start a conversation with any person ends with an error message - `Body param "roomid" or "username" is required [error-room-param-not-provided]`

video2gif_20181208_190737

### PR DESCRIPTION
**Pull request by dabbler011**
@RocketChat/android

Closes #1912 

chatRoom object was instantiated with empty id. So, toDirectMessage() was called with empty id in clickListeners.

Works fine now.

### CODE REVIEW

**Comment by rafaelks** [comment]
Thanks for the PR, but this problem fixes the alert, but you can't chat with the person because there's no "Send" button or the emoji button doesn't work.

**Comment by dabbler011** [comment]
The problem was because the newly created room was not added in the database due to which listeners were not instantiated. I suppose refreshing chat rooms in db before accessing them fixes the issue. I have commited changes for the same.

@rafaelks please review.

**Comment by rafaelks** [comment]
@dabbler011 "Send button" still don't show up on new conversations.

**Comment by dabbler011** [comment]
@rafaelks are you sure? As it is working just fine for me. 

video

**Comment by rafaelks** [comment]
Just tested the latest build here, check it out:

**Comment by leonardoaramaki** [comment]
@dabbler011 change the following method on `ChatRoomPresenter` to this and we should be good to merge:
```
private suspend fun subscribeRoomChanges() {
    withContext(CommonPool + strategy.jobs) {
            chatRoomId?.let {
                manager.addRoomChannel(it, roomChangesChannel)
                for (room in roomChangesChannel) {
                    dbManager.getRoom(room.id)?.let {
                        view.onRoomUpdated(roomMapper.map(chatRoom = it, showLastMessage = true))
                    }
                }
            }
        }
}
```

**Review by leonardoaramaki — CHANGES_REQUESTED** [review]
Changes pointed out comments.

**Comment by dabbler011** [comment]
@leonardoaramaki updated the method.

**Comment by leonardoaramaki** [comment]
Thanks @dabbler011. Testing

**Review by leonardoaramaki — APPROVED** [review]

**Pull request merged**
