### PR TITLE
[I18N] update IT strings.xml

### LINKED ISSUE #1909: Update all strings.xml
## Description

Some strings.xml files are not updated and missing some new translations

**Would you like to work on the issue?**
- Yes

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
Closes #1909

### CODE REVIEW

**Comment by rafaelks** [comment]
That doesn't look like Italian 🤔

**Comment by GOVINDDIXIT** [comment]
Oops, my translator was set to irish 😰

**Comment by GOVINDDIXIT** [comment]
@rafaelks Updated. Pls review

**Review by philipbrito — APPROVED** [review]
Thanks @GOVINDDIXIT for submitting this PR.

**Pull request merged**
